### PR TITLE
Changing module.exports into a function that expects a year

### PR DESCRIPTION
**Pull request by TheIronDev**
I noticed the output returned the days of the week for 2016. I
wanted to make this a little more flexible and future proof, but I
couldn't think of a good solution to fix this without changing what
the main scripts file returns.

But, ... One possible solution is for module.exports to export the result
of calling the function for the current year.

Something like:

``` javascript
var now = new Date();
currentYear = now.getFullYear();
module.exports = getHolidays(currentYear);
```

LMKWYT and I'll make updates accordingly. :+1:

### CODE REVIEW

**Comment by hemanth** [comment]
Completely missed the days! 

How about?

``` js

let days = 'Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday'.split(",");
let holidays =  [{},{}];
holidays = holidays.map( h => {
  h.day = days[new Date(`${h.day.date} ${(new Date()).getFullYear()}`).getDay()];
  return h;
});
```

**Comment by TheIronDev** [comment]
@hemanth Yeah I totally forgot how behind node 0.10 was, I don't even think `let` is valid for node 0.10 without the harmony flag, so.... I'll have a backward-version safe fix in a minute

**Comment by hemanth** [comment]
@TheIronDeveloper How about doing [this](https://github.com/hemanth/indian-holidays/pull/1#issuecomment-215644541) and chaining the node engine to `>=4` ?

**Comment by TheIronDev** [comment]
Sure, I'm happy to do that!

**Comment by TheIronDev** [comment]
I pulled out the date as a variable for readability, and fixed the date order (it starts on Sunday, at least for my current locale :x )

**Comment by hemanth** [comment]
@TheIronDeveloper Thank you! 💯

**Comment by TheIronDev** [comment]
np, glad to help out

**Pull request merged**
